language: php

services:
  - docker

php:
  - '7.2'

git:
  depth: 1

before_install:
  - curl -Ls https://raw.githubusercontent.com/unb-libraries/dockworker/3.x/scripts/travis/init.sh | bash
  - composer install

script:
  - set -e
  - vendor/bin/dockworker local:build-test
  - vendor/unb-libraries/dockworker/scripts/kubectl/init.sh
  - vendor/bin/dockworker image:deploy $TRAVIS_BRANCH

notifications:
  slack:
    rooms:
      secure: AjbZ0hrzHGv5SdP7ws4S2M8sB+YxwjbP/sTx0IruRXo0dEZbfsW4kjwUWFMlIdk78lSpdjE+mO7chpbhXFE6YK9Y1lvDHPZP1BEYawHuklPyRrIoie3Gg3nr12kxTP8JHoxeyRs7WeCCyMz86xFykKIo5iSBP7qxb2V2RH+teDXS9xrqjREWcxLmXDYwpWt/P7CB9Mhz+ufcelLcT0dH7+FMlRRhsLyp6dJJm/ng0Exaj4oxGd208KwREygFUQ/4D2ZebYiPYybng+dwlWJi54aNMmGgw4KC+8mpDw6i1Qr9t1HYx/fMh913EVUQWJRR435NNWOUOmauO6U5fGSNTacPHIzvB4ejMscImjsXPc1TfqLxOBfZM13Uc958S4ghWjtjdSQCyTxQcythYgYqiMOA8TFVtriUNfAQ03RMcKmD5zqybiED04iV/NQw1XIT8ieXe0OjSMXaf1VGT3T/SyIyvrhONd+xS6GGRZ+Yjqx2ZfrWXhDVSkdhB9JkT0Y6vdF4OJw+yh9VP5mHTiKWpm2oq+JUGdzgyNzeILVcB+mn+FBst3xMuK4ux5pWGVqf8uXUZKFKWwrlrkZijITrdxT5cBg+ukvAxrL0wMZRcasp0HTOWPmSYJEPpGrHqBvoVd8wybtmzlI+t6oTKOow4VBIQSCiv4ZbiFsvaBq9ihg=
    on_start: always
    on_success: always
