version: '3.6'

services:
  lastshift.lib.unb.ca:
    build:
      context: .
    restart: always
    container_name: lastshift.lib.unb.ca
    expose:
      - "80"
    ports:
      - "3112:80"
    environment:
      - LOCAL_HOSTNAME=local-lastshift.lib.unb.ca
      - LOCAL_PORT=3112
    networks:
      - lastshift.lib.unb.ca

networks:
  lastshift.lib.unb.ca:
    name: lastshift.lib.unb.ca
