services:
  lastshift.lib.unb.ca:
    build:
      context: .
    restart: always
    container_name: lastshift.lib.unb.ca
    expose:
      - "80"
    ports:
      - "3112:80"
    env_file:
      - ./env/jekyll.env
    networks:
      - lastshift.lib.unb.ca
    volumes:
      - ./.html:/app/html

  builder:
    build:
      context: builder
    restart: always
    container_name: builder.lastshift.lib.unb.ca
    networks:
      - lastshift.lib.unb.ca
    volumes:
      - ./build/src:/build/src
      - ./.html:/dist
networks:
  lastshift.lib.unb.ca:
    name: lastshift.lib.unb.ca
