apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    tier: lastshift
    uri: lastshift.lib.unb.ca
  name: lastshift-lib-unb-ca
  namespace: prod
spec:
  selector:
    matchLabels:
      uri: lastshift.lib.unb.ca
  replicas: 1
  revisionHistoryLimit: 2
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nginx
        tier: jekyll
        uri: lastshift.lib.unb.ca
    spec:
      nodeSelector:
        deployenv: prod
      containers:
        -
          env:
            -
              name: DEPLOY_ENV
              value: prod
          image: "||DEPLOYMENTIMAGE||"
          imagePullPolicy: Always
          name: lastshift-lib-unb-ca
          ports:
            -
              containerPort: 80
      priorityClassName: high-priority-services
      restartPolicy: Always
