apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jekyll
    instance: lastshift.lib.unb.ca
    tier: lastshift
    uri: dev-lastshift.lib.unb.ca
  name: lastshift-lib-unb-ca
  namespace: dev
spec:
  selector:
    matchLabels:
      uri: dev-lastshift.lib.unb.ca
  replicas: 1
  revisionHistoryLimit: 2
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: jekyll
        instance: lastshift.lib.unb.ca
        tier: lastshift
        uri: dev-lastshift.lib.unb.ca
    spec:
      nodeSelector:
        deploy_dev: 'true'
      containers:
        -
          env:
            -
              name: DEPLOY_ENV
              value: dev
          image: "||DEPLOYMENTIMAGE||"
          imagePullPolicy: Always
          name: lastshift-lib-unb-ca
          ports:
            -
              containerPort: 80
      priorityClassName: dev-high-priority-services
      imagePullSecrets:
        -
          name: github-container-registry-auth
      restartPolicy: Always
